//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_ingredients()
        {
            this.content_order_ingredients = new HashSet<content_order_ingredients>();
        }
    
        public int id { get; set; }
        public System.DateTime order_time { get; set; }
        public System.DateTime execute_time { get; set; }
        public Nullable<int> provider_id { get; set; }
        public int status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<content_order_ingredients> content_order_ingredients { get; set; }
        public virtual providers providers { get; set; }
    }
}
