//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        public int id { get; set; }
        public int menu_id { get; set; }
        public int ingredient_id { get; set; }
        public int count { get; set; }
        public Nullable<int> unit_of_measurement_id { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual menu menu { get; set; }
        public virtual units_of_measurement units_of_measurement { get; set; }
    }
}
