//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment_ingredients
    {
        public int id { get; set; }
        public Nullable<int> content_ingredients_id { get; set; }
        public Nullable<int> storage_ingredient_id { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        public virtual content_order_ingredients content_order_ingredients { get; set; }
        public virtual storage_ingredient storage_ingredient { get; set; }
    }
}
