//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class vContent
    {
        public int id { get; set; }
        public string name { get; set; }
        public int count { get; set; }
        public string units_of_measurement { get; set; }
        public int provider_price { get; set; }
        public Nullable<System.DateTime> execute_time { get; set; }
    }
}
