//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrder
    {
        public string provider { get; set; }
        public System.DateTime order_time { get; set; }
        public System.DateTime execute_time { get; set; }
        public string status { get; set; }
    }
}
