//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        public int id { get; set; }
        public int id_content { get; set; }
        public int id_storage_ingredient { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual content_order_ingredients content_order_ingredients { get; set; }
        public virtual storage_ingredient storage_ingredient { get; set; }
    }
}
