//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_test.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage_ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public storage_ingredient()
        {
            this.shipment = new HashSet<shipment>();
        }
    
        public int id { get; set; }
        public int count { get; set; }
        public Nullable<int> unit_of_measurement_id { get; set; }
        public Nullable<int> ingredient_id { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment> shipment { get; set; }
        public virtual units_of_measurement units_of_measurement { get; set; }
    }
}
